// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyChVdw4muUUJo1DKYQoNmKYUctU7pxHdcg',
    appId: '1:454513114027:web:29b2ead2b349e89504b0ee',
    messagingSenderId: '454513114027',
    projectId: 'bat2211c1',
    authDomain: 'bat2211c1.firebaseapp.com',
    storageBucket: 'bat2211c1.firebasestorage.app',
    measurementId: 'G-XPS2ENWG7J',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAiHyul6bIWgORwB-jYS1CtLTVrlRD8fRQ',
    appId: '1:454513114027:android:9aed456675c405e204b0ee',
    messagingSenderId: '454513114027',
    projectId: 'bat2211c1',
    storageBucket: 'bat2211c1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCIEHvfoqZQRLGYwQ_upGeBGHzV43HPOz8',
    appId: '1:454513114027:ios:201197c3a718ff9104b0ee',
    messagingSenderId: '454513114027',
    projectId: 'bat2211c1',
    storageBucket: 'bat2211c1.firebasestorage.app',
    iosBundleId: 'com.example.userAuthenticationAuthorization',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCIEHvfoqZQRLGYwQ_upGeBGHzV43HPOz8',
    appId: '1:454513114027:ios:201197c3a718ff9104b0ee',
    messagingSenderId: '454513114027',
    projectId: 'bat2211c1',
    storageBucket: 'bat2211c1.firebasestorage.app',
    iosBundleId: 'com.example.userAuthenticationAuthorization',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyChVdw4muUUJo1DKYQoNmKYUctU7pxHdcg',
    appId: '1:454513114027:web:b0b7592cc96befbf04b0ee',
    messagingSenderId: '454513114027',
    projectId: 'bat2211c1',
    authDomain: 'bat2211c1.firebaseapp.com',
    storageBucket: 'bat2211c1.firebasestorage.app',
    measurementId: 'G-7XHZTVFYCH',
  );
}
